services:
  ecommerce:
    build: .
    container_name: api_ecommerce
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db_ecommerce:5432/db_ecommerce
      - DB_USERNAME=matheus
      - DB_PASSWORD=secret
  postgres:
    image: bitnami/postgresql
    container_name: db_ecommerce
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=matheus
      - POSTGRESQL_PASSWORD=secret
      - POSTGRESQL_DATABASE=db_ecommerce
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d db_ecommerce -U matheus"]
      interval: 10s
      timeout: 5s
      retries: 5
